### PR TITLE
Don't store job related metrics by default

### PR DESCRIPTION
**Pull request by vetinari**
Check job related pods and containers for the "zmon.io/job-metric-stored"
annotation and ignore those where it's not set.

Signed-off-by: Hanno Hecker <hanno@zalando.de>

### CODE REVIEW

**Comment by pitr** [comment]
:+1:

**Comment by vetinari** [comment]
:+1:

**Comment by pitr** [comment]
We don't read the value of `zalando.org/zmon-job-metric-stored` annotation?

**Comment by vetinari** [comment]
:+1:

**Pull request merged**
